// Writes web/public/data/materiality.json from data/materiality.csv --
// generated once and committed (like the fixture files), not regenerated by
// `npm run data`: materiality.csv is a hand-curated judgement call, not a
// DB-refresh artifact (see pipeline/materiality.py's own docstring: "This
// is a JUDGEMENT, not a derivation").
//
// Run via `npm run materiality` from web/.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCsv } from "./csv";
import { assertIndicatorColumnsKnown, deriveMaterialityWeights } from "../src/scoring/materiality";
import { pythonDefaultWeights } from "../src/scoring/weights";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..");
const CSV_PATH = resolve(REPO_ROOT, "data", "materiality.csv");
const OUT_PATH = resolve(__dirname, "..", "public", "data", "materiality.json");

function main() {
  const rows = parseCsv(readFileSync(CSV_PATH, "utf-8"));
  if (rows.length === 0) throw new Error(`no rows parsed from ${CSV_PATH}`);
  assertIndicatorColumnsKnown(Object.keys(rows[0]));

  // pythonDefaultWeights combines the CSV's per-sector P1 weights with
  // Python's fixed P2/P3 WEIGHTS dicts and equal pillar weights -- this
  // file is the app's actual default scoring weights, not an opt-in
  // "materiality mode" among equally-valid choices. See its own doc
  // comment in weights.ts.
  const weights = pythonDefaultWeights(deriveMaterialityWeights(rows));
  const weightsObj = Object.fromEntries(weights);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(weightsObj));

  const kb = (Buffer.byteLength(JSON.stringify(weightsObj), "utf-8") / 1024).toFixed(1);
  console.log(`wrote ${OUT_PATH} -- ${weights.size} sectors, ${kb} KB`);
  console.log("P1 sub-score weights per sector (P2/P3 are Python's fixed WEIGHTS dicts, same for every sector):");
  for (const [sector, w] of weights) {
    const p1 = Object.entries(w.subscores)
      .filter(([id]) => id.startsWith("p1_"))
      .map(([id, v]) => `${id}=${v}`)
      .join(" ");
    console.log(`  ${sector.padEnd(24)} ${p1}`);
  }
}

main();
