// Writes web/public/data/materiality.json from data/materiality.csv --
// generated once and committed (like the fixture files), not regenerated by
// `npm run data`: materiality.csv is a hand-curated judgement call, not a
// DB-refresh artifact (see pipeline/materiality.py's own docstring: "This
// is a JUDGEMENT, not a derivation").
//
// Run via `npm run materiality` from web/.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCsv } from "./csv";
import { assertIndicatorColumnsKnown, deriveMaterialityWeights } from "../src/scoring/materiality";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..");
const CSV_PATH = resolve(REPO_ROOT, "data", "materiality.csv");
const OUT_PATH = resolve(__dirname, "..", "public", "data", "materiality.json");

function main() {
  const rows = parseCsv(readFileSync(CSV_PATH, "utf-8"));
  if (rows.length === 0) throw new Error(`no rows parsed from ${CSV_PATH}`);
  assertIndicatorColumnsKnown(Object.keys(rows[0]));

  const weights = deriveMaterialityWeights(rows);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(weights));

  const kb = (Buffer.byteLength(JSON.stringify(weights), "utf-8") / 1024).toFixed(1);
  console.log(`wrote ${OUT_PATH} -- ${Object.keys(weights).length} sectors, ${kb} KB`);
  console.log("pillar weights per sector:");
  for (const [sector, w] of Object.entries(weights)) {
    console.log(
      `  ${sector.padEnd(24)} P1=${w.pillars.P1.toFixed(1).padStart(5)}  ` +
        `P2=${w.pillars.P2.toFixed(1).padStart(5)}  P3=${w.pillars.P3.toFixed(1).padStart(5)}`
    );
  }
}

main();
