// The oracle check the task's frontend-contract.md originally described:
// "score.py becomes an oracle... npm run verify:oracle asserts TS and
// Python agree within 1e-6" -- except unlike web/scripts/verify-oracle.ts
// (a separate, narrower "Task 8" effort checking sub-scores only, at
// default/equal-within-pillar weights, against a not-yet-written
// score_calculation/score.py -- see that file's own header), THIS script
// diffs computeScores() against the FOUR pillar CSVs score_calculation/
// already produces today:
//   data/environmental_scores.csv, data/transition_scores.csv,
//   data/governance_scores.csv, data/final_scores.csv
// at Python's REAL production weights, not a default/equal placeholder:
//   - P1 sub-scores: environmental_score.py's own per-sector materiality
//     weights (data/materiality.csv, via deriveMaterialityWeights).
//   - P2/P3 sub-scores: transition_score.py's/governance_score.py's fixed
//     WEIGHTS dicts (registry.ts's PYTHON_P2_WEIGHTS/PYTHON_P3_WEIGHTS).
//   - Pillars: final_score.py's fixed equal 1/3 split.
// See weights.ts's pythonDefaultWeights, which builds exactly this
// per-sector WeightsState Map.
//
// Compares every registry sub-score's `.score` (not `.rawValue` -- Python's
// own *_score columns are the already-percentiled/oriented 0-100 values,
// same definition as SubScoreResult.score), each pillar's `.score` and
// `.scoreRaw`, and the final composite, per ticker. Reports EVERY
// mismatching (ticker, column) pair, not just a pass/fail -- per the task,
// "the mismatches are how you find what's still missed."
//
// Run via `npm run verify:scoring-parity` (needs data/*.csv already
// generated by score_calculation's own three pillar scripts + final_score.py,
// and web/public/data/matrix.json generated by `npm run data`).
import { readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCsv } from "./csv";
import { computeScores } from "../src/scoring/pipeline";
import { deriveMaterialityWeights } from "../src/scoring/materiality";
import { pythonDefaultWeights } from "../src/scoring/weights";
import { REGISTRY } from "../src/scoring/registry";
import type { MatrixPayload } from "../src/scoring/types";

const TOLERANCE = Number(process.argv.find((a) => a.startsWith("--tolerance="))?.split("=")[1] ?? 1e-6);
const MAX_PRINTED_PER_COLUMN = 15;

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..");
const DATA_DIR = resolve(REPO_ROOT, "data");
const MATRIX_PATH = resolve(REPO_ROOT, "web", "public", "data", "matrix.json");
const MATERIALITY_CSV_PATH = resolve(DATA_DIR, "materiality.csv");

const SUBSCORE_CSV: Record<string, { file: string; column: string }> = {
  p1_carbon_intensity: { file: "environmental_scores.csv", column: "carbon_intensity_score" },
  p1_energy_mix: { file: "environmental_scores.csv", column: "energy_mix_score" },
  p1_resource_waste: { file: "environmental_scores.csv", column: "resource_waste_score" },
  p1_input_efficiency: { file: "environmental_scores.csv", column: "input_efficiency_score" },
  p2_carbon_price_exposure: { file: "transition_scores.csv", column: "carbon_price_exposure_score" },
  p2_sector_exposure: { file: "transition_scores.csv", column: "sector_exposure_score" },
  p2_regulatory_momentum: { file: "transition_scores.csv", column: "regulatory_commitment_score" },
  p2_transition_affordability: { file: "transition_scores.csv", column: "transition_affordability_score" },
  p3_capital_stewardship: { file: "governance_scores.csv", column: "capital_stewardship_score" },
  p3_climate_governance: { file: "governance_scores.csv", column: "climate_governance_score" },
  p3_exec_compensation: { file: "governance_scores.csv", column: "compensation_alignment_score" },
  p3_board_independence: { file: "governance_scores.csv", column: "board_independence_score" },
  p3_controversy_flags: { file: "governance_scores.csv", column: "controversy_score" },
};

const PILLAR_CSV: Record<string, { file: string; scoreColumn: string; rawColumn: string }> = {
  P1: { file: "environmental_scores.csv", scoreColumn: "environmental_score", rawColumn: "environmental_score_raw" },
  P2: { file: "transition_scores.csv", scoreColumn: "transition_score", rawColumn: "transition_score_raw" },
  P3: { file: "governance_scores.csv", scoreColumn: "governance_score", rawColumn: "governance_score_raw" },
};

function readCsv(fileName: string): Map<string, Record<string, string>> {
  const path = resolve(DATA_DIR, fileName);
  if (!existsSync(path)) {
    console.error(`Missing ${path}. Run the matching score_calculation module first, e.g.:`);
    console.error(`  python3 -m score_calculation.environmental.environmental_score`);
    console.error(`  python3 -m score_calculation.transition.transition_score`);
    console.error(`  python3 -m score_calculation.governance.governance_score`);
    console.error(`  python3 -m score_calculation.final_score`);
    process.exit(1);
  }
  const rows = parseCsv(readFileSync(path, "utf-8"));
  return new Map(rows.map((r) => [r.ticker, r]));
}

/** Empty string (pandas' NaN-to-CSV convention) -> null; otherwise a number. */
function parsePythonValue(raw: string | undefined): number | null {
  if (raw === undefined || raw === "") return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

interface Mismatch {
  ticker: string;
  label: string;
  ts: number | null;
  python: number | null;
  diff: number | null;
}

function compareColumn(
  label: string,
  tickers: readonly string[],
  tsByTicker: Map<string, number | null>,
  pythonRows: Map<string, Record<string, string>>,
  pythonColumn: string
): { compared: number; mismatches: Mismatch[] } {
  let compared = 0;
  const mismatches: Mismatch[] = [];
  for (const ticker of tickers) {
    const pythonRow = pythonRows.get(ticker);
    if (!pythonRow) continue; // ticker not in this Python output at all -- not this script's concern
    const python = parsePythonValue(pythonRow[pythonColumn]);
    const ts = tsByTicker.get(ticker) ?? null;
    compared++;
    if (ts === null && python === null) continue; // both agree "no value" -- a match
    const diff = ts === null || python === null ? null : Math.abs(ts - python);
    if (diff === null || diff > TOLERANCE) {
      mismatches.push({ ticker, label, ts, python, diff });
    }
  }
  return { compared, mismatches };
}

function main() {
  if (!existsSync(MATRIX_PATH)) {
    console.error(`No matrix.json at ${MATRIX_PATH}. Run "npm run data" first.`);
    process.exit(1);
  }
  if (!existsSync(MATERIALITY_CSV_PATH)) {
    console.error(`No materiality.csv at ${MATERIALITY_CSV_PATH}.`);
    process.exit(1);
  }

  const payload = JSON.parse(readFileSync(MATRIX_PATH, "utf-8")) as MatrixPayload;
  const materialityRows = parseCsv(readFileSync(MATERIALITY_CSV_PATH, "utf-8"));
  const weights = pythonDefaultWeights(deriveMaterialityWeights(materialityRows));

  const tsScores = computeScores(payload.companies, weights);
  const tickers = payload.companies.map((c) => c.ticker);

  const envRows = readCsv("environmental_scores.csv");
  const traRows = readCsv("transition_scores.csv");
  const govRows = readCsv("governance_scores.csv");
  const finalRows = readCsv("final_scores.csv");
  const csvByFile: Record<string, Map<string, Record<string, string>>> = {
    "environmental_scores.csv": envRows,
    "transition_scores.csv": traRows,
    "governance_scores.csv": govRows,
    "final_scores.csv": finalRows,
  };

  let totalCompared = 0;
  const allMismatches: Mismatch[] = [];
  const perColumnSummary: { label: string; compared: number; mismatches: number }[] = [];

  // --- sub-scores ---
  for (const sub of REGISTRY) {
    const target = SUBSCORE_CSV[sub.id];
    if (!target) {
      console.warn(`No CSV mapping for registry sub-score "${sub.id}" -- skipping (update SUBSCORE_CSV).`);
      continue;
    }
    const tsByTicker = new Map<string, number | null>();
    for (const ticker of tickers) {
      const result = tsScores.get(ticker);
      const subResult = result?.pillars[sub.pillar].subScores.find((s) => s.id === sub.id);
      tsByTicker.set(ticker, subResult?.score ?? null);
    }
    const { compared, mismatches } = compareColumn(
      `${sub.pillar}/${sub.id}`,
      tickers,
      tsByTicker,
      csvByFile[target.file],
      target.column
    );
    totalCompared += compared;
    allMismatches.push(...mismatches);
    perColumnSummary.push({ label: `${sub.pillar}/${sub.id}`, compared, mismatches: mismatches.length });
  }

  // --- pillar scores (post disclosure-penalty) and raw scores ---
  for (const pillar of ["P1", "P2", "P3"] as const) {
    const target = PILLAR_CSV[pillar];
    const scoreByTicker = new Map<string, number | null>();
    const rawByTicker = new Map<string, number | null>();
    for (const ticker of tickers) {
      const result = tsScores.get(ticker);
      scoreByTicker.set(ticker, result?.pillars[pillar].score ?? null);
      rawByTicker.set(ticker, result?.pillars[pillar].scoreRaw ?? null);
    }
    const scoreCheck = compareColumn(`${pillar} (final)`, tickers, scoreByTicker, csvByFile[target.file], target.scoreColumn);
    const rawCheck = compareColumn(`${pillar} (raw)`, tickers, rawByTicker, csvByFile[target.file], target.rawColumn);
    for (const check of [scoreCheck, rawCheck]) {
      totalCompared += check.compared;
      allMismatches.push(...check.mismatches);
    }
    perColumnSummary.push(
      { label: `${pillar} (final)`, compared: scoreCheck.compared, mismatches: scoreCheck.mismatches.length },
      { label: `${pillar} (raw)`, compared: rawCheck.compared, mismatches: rawCheck.mismatches.length }
    );
  }

  // --- final composite ---
  {
    const tsByTicker = new Map<string, number | null>();
    for (const ticker of tickers) tsByTicker.set(ticker, tsScores.get(ticker)?.composite ?? null);
    const { compared, mismatches } = compareColumn("final_score", tickers, tsByTicker, finalRows, "final_score");
    totalCompared += compared;
    allMismatches.push(...mismatches);
    perColumnSummary.push({ label: "final_score", compared, mismatches: mismatches.length });
  }

  // --- report ---
  console.log(`Compared ${totalCompared} (ticker, column) pairs across ${perColumnSummary.length} columns, tolerance ${TOLERANCE}.\n`);
  console.log("Per-column summary (compared / mismatches):");
  for (const s of perColumnSummary) {
    const flag = s.mismatches > 0 ? "FAIL" : "pass";
    console.log(`  [${flag}] ${s.label.padEnd(28)} ${s.compared.toString().padStart(4)} compared, ${s.mismatches} mismatch(es)`);
  }

  if (allMismatches.length === 0) {
    console.log(`\nPASS -- TS and Python agree within ${TOLERANCE} on every compared (ticker, column) pair.`);
    return;
  }

  console.log(`\nFAIL -- ${allMismatches.length} mismatching (ticker, column) pair(s). Detail by column:\n`);
  const byLabel = new Map<string, Mismatch[]>();
  for (const m of allMismatches) {
    const arr = byLabel.get(m.label) ?? [];
    arr.push(m);
    byLabel.set(m.label, arr);
  }
  for (const [label, mismatches] of byLabel) {
    const finite = mismatches.filter((m) => m.diff !== null).map((m) => m.diff!);
    const maxDiff = finite.length ? Math.max(...finite) : null;
    const meanDiff = finite.length ? finite.reduce((a, b) => a + b, 0) / finite.length : null;
    console.log(
      `${label}: ${mismatches.length} mismatch(es)` +
        (maxDiff !== null ? `, max diff ${maxDiff.toFixed(4)}, mean diff ${meanDiff!.toFixed(4)}` : "")
    );
    for (const m of mismatches.slice(0, MAX_PRINTED_PER_COLUMN)) {
      console.log(`    ${m.ticker}: TS=${m.ts ?? "null"} python=${m.python ?? "null"} diff=${m.diff?.toFixed(4) ?? "n/a"}`);
    }
    if (mismatches.length > MAX_PRINTED_PER_COLUMN) {
      console.log(`    ... and ${mismatches.length - MAX_PRINTED_PER_COLUMN} more`);
    }
  }
  process.exit(1);
}

main();
