// Loads web/public/data/materiality.json (generated by
// scripts/make-materiality.ts from data/materiality.csv). Unlike useMatrix,
// there is no fixture fallback here: a 404 just means materiality-weighted
// mode is unavailable in the UI, it must never block the rest of the app --
// the manual/preset weight sliders keep working regardless.
import { useEffect, useState } from "react";
import type { WeightsState } from "../scoring/pipeline";

export interface MaterialityState {
  status: "loading" | "ready" | "unavailable";
  /** sector -> WeightsState, plus the CSV's rationale string per sector. */
  weights: Map<string, WeightsState & { rationale: string }> | null;
}

export function useMaterialityWeights(): MaterialityState {
  const [state, setState] = useState<MaterialityState>({ status: "loading", weights: null });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/data/materiality.json");
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const raw = (await res.json()) as Record<string, WeightsState & { rationale: string }>;
        if (!cancelled) setState({ status: "ready", weights: new Map(Object.entries(raw)) });
      } catch {
        if (!cancelled) setState({ status: "unavailable", weights: null });
      }
    })();
    return () => { cancelled = true; };
  }, []);

  return state;
}
