// Loads web/public/data/revenue_growth.json (generated by
// score_calculation/revenue_growth.py). This one field can't come from
// matrix.json -- that payload pins every field to one fiscal year per
// company, so a multi-year CAGR has to be computed separately, straight off
// the observations database, and shipped as its own small file. Same
// no-fixture-fallback pattern as useMaterialityWeights: a 404 just means the
// Revenue CAGR column/filter is unavailable, it must never block the rest
// of the page.
import { useEffect, useState } from "react";

export interface RevenueGrowthState {
  status: "loading" | "ready" | "unavailable";
  /** ticker -> revenue CAGR 2021->2025, as a percentage (e.g. 3.28 = 3.28%/yr). */
  cagrByTicker: Map<string, number> | null;
}

export function useRevenueGrowth(): RevenueGrowthState {
  const [state, setState] = useState<RevenueGrowthState>({ status: "loading", cagrByTicker: null });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/data/revenue_growth.json");
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const raw = (await res.json()) as Record<string, number>;
        if (!cancelled) setState({ status: "ready", cagrByTicker: new Map(Object.entries(raw)) });
      } catch {
        if (!cancelled) setState({ status: "unavailable", cagrByTicker: null });
      }
    })();
    return () => { cancelled = true; };
  }, []);

  return state;
}
